
                <div class="span10 abstract">
                    <h2>Part 1: Project core</h2>
                    <p>This this part produces the most basic ZF2 application. 
                        Some pointers and considerations are set out as a
                        foundation upon which developers can build.</p>
                    
                    <h2>Part 2: Adding MmaIrc module</h2>
                    <p>This part provides an example module, MmaIrc (which 
                        converts chat logs into a digest). The process sets out 
                        how to plug into a project, something of DI, the module
                        config file, and Module.php.</p>
                    
                    <h2>Part 3: Adding a third module</h2>
                    <p>Part 3 rehearses adding further modules.</p>
                    
                    <h2>Part 4: Adding ZfcUser module for login</h2>
                    <p>Login authentication and security,courtesy of Evan 
                        Coury's exceptional talents and his ZfcUser. This module 
                        takes the hard work out of this crucial part of 
                        application development.</p>
                    
                    <h2>Part 5: Adding authorisation and ACL</h2>
                    <p>Having logged in, the authorisation and ACL module 
                        defines who can access what, where, and how. Includes 
                        ACL compliant bread-crumb navigation trails.</p>
                    
                    <h2>Part 6: Adding a module with database access</h2>
                    <p>This part not only employs database access techniques in
                        a simple application, but in conjunction with ZfcUser, 
                        authorisation and ACL, how to limit access for users 
                        without privileges.</p>
                    
                    <h2>Part 7: Pushing results to new View mechanisms</h2>
                    <p>This part takes a look at how the new "View Model" 
                        operates and communicates with Controllers.</p>
                </div>

                <div class="row">
                    <div class="span4 rightcol">
                        <p>
                            <a class="btn primary large"
                               href="https://github.com/mike-a/zf2-tutorial-pt1">
                                Fork Part 1 from GitHub &raquo;
                            </a>
                        </p>

                        <h2>Modules</h2>
                        <p>This project will make use of several ZF2 modules:</p>
                        <ul>
                            <li>
                                <a href="#">MmaIrc</a>
                            </li>
                            <li>
                                <a href="https://github.com/ZF-Commons/ZfcUser">ZfcUser</a>
                            </li>
                            <li>
                                <a href="https://github.com/ZF-Commons/ZfcBase">ZfcBase</a>
                            </li>
                            <li>
                                <a href="https://github.com/SpiffyJr/SpiffyDoctrine">
                                    SpiffyDoctrine</a>
                            </li>
                            <li>
                                <a href="https://github.com/SpiffyJr/SpiffyDoctrineORM">
                                    SpiffyDoctrineORM</a>
                            </li>
                        </ul>

                        <h2>#zftalk.2</h2>
                        <p>Serious developers can join in with ZF2 beta
                            development at... irc://irc.freenode.org:6665/zftalk.2.
                        </p>
                    </div>
                </div>
